name: EPL Data - Scrape, Clean, Process, Analyze, Predict
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 1 * * *

jobs:
  Scrape-EPL-Data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3                           
      - name: Get latest packages and updates
        run: sudo apt-get update && sudo apt-get upgrade -y
      - name: Install Firefox and Geckodriver
        run: |
          sudo apt install firefox
          sudo apt-get install firefox-geckodriver
      - name: Install Required Pip Modules
        run: pip3 install -r requirements.txt
        working-directory: ./epl/scrape-scripts
      - name: Run Scrape Script
        run: |
          chmod +x scraper.sh
          ./scraper.sh
        working-directory: ./epl/scrape-scripts
      - uses: actions/upload-artifact@v3
        with:
          name: epl-raw-data
          path: ./epl/scraped-data
      - name: Commit Build Artifacts
        run: |
          git config --global user.name "charles-adedotun"
          git config --global user.email "charles.adedotun8@gmail.com"
          git fetch
          git add .
          git commit -a -m "CI commit" --allow-empty
          git push

  Upload-To-Kaggle:
    needs:
      - Scrape-EPL-Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: epl-raw-data
      - name: Display structure of downloaded files
        run: ls -R
      - name: Upload datasets
        uses: jaimevalero/push-kaggle-dataset@v3
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        with:
          id:  "charlesadedotun/epl-data-2021-22"
          title: "English Premier League Data 2021/22"
          subtitle: "EPL Records 2021/2022 Season"
          description: "## English Premier League Records for 2021/22 season scarpped from https://www.mykhel.com amd the Premier League website, https://www.premierleague.com/."
          files:  "*.csv"
          is_public: true

  Clean-Data:
    needs:
      - Scrape-EPL-Data
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Install tidyverse
        run: Rscript -e 'install.packages("tidyverse")'
      - name: Install tinytex
        run: |
          Rscript -e 'install.packages("tinytex")'
          Rscript -e 'tinytex::install_tinytex()'
      - name: Run and Render Clean Scripts
        run: |
          chmod +x cleaner.sh
          ./cleaner.sh
        working-directory: ./epl/clean-scripts
      - uses: actions/upload-artifact@v3
        with:
          name: epl-yellow-card-data
          path: ./epl/cleaned-data
      - name: Commit Build Artifacts
        run: |
          git config --global user.name "charles-adedotun"
          git config --global user.email "charles.adedotun8@gmail.com"
          git fetch
          git pull
          git add .
          git commit -a -m "CI commit" --allow-empty
          git push

  Upload-YellowCard-Data-To-Kaggle:
    needs:
      - Clean-Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: epl-yellow-card-data
      - name: Display structure of downloaded files
        run: ls -R
      - name: Upload datasets
        uses: jaimevalero/push-kaggle-dataset@v3
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        with:
          id:  "charlesadedotun/epl-yellow-card-data-2021-22"
          title: "EPL Yellow Card Per Match Data"
          subtitle: "EPL Booking Records per match 2021/2022 Season"
          description: "## English Premier League Yellow Card per match data for teams and referees 2021/22 season scarpped from https://www.mykhel.com amd the Premier League website, https://www.premierleague.com/."
          files:  "*.csv"
          is_public: true
