name: Yelow Card Record Scrapper
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 1 * * *
jobs:
  Scrap-Yellow-Card-Data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3                              
      - name: Get latest packages and updates
        run: sudo apt-get update && sudo apt-get upgrade -y
      - name: Install Firefox and Geckodriver
        run: |
          sudo apt install firefox
          sudo apt-get install firefox-geckodriver
      - name: Install Required Pip Modules
        run: pip3 install -r requirements.txt
      - name: Run Scrappers
        run: |
          cd epl/yellow-cards
          chmod +x runner.sh
          ./runner.sh
      - uses: actions/upload-artifact@v3
        with:
          name: epl-yellow-cards
          path: epl/yellow-cards/data
  Upload-To-Kaggle:
    needs:
      - Scrap-Yellow-Card-Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: epl-yellow-cards
      - name: Display structure of downloaded files
        run: ls -R
      - name: Upload datasets
        uses: jaimevalero/push-kaggle-dataset@v3 # This is the action
        env:
          # Do not leak your credentials.
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        with:
          id:  "charlesadedotun/epl-yellow-cards-data"
          title: "EPL Yellow Card Data 2021/22"
          subtitle: "EPL Yellow Card Records for Teams and Referees"
          description: "## Premier League Yellow Card Records for 2021/22 season <br/>Source https://www.premierleague.com and https://sports.ndtv.com <br/> "
          files:  "*.csv"
          is_public: true
